---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: sleep infinity
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - verify
    - destroy
